version: '3'
services:
  app:
    image: node:latest
    environment:
      - DOCKER_NODE_ENV
      - NODE_OPTIONS=--max-old-space-size=4096 
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - ${DOCKER_APACHE_PORT}:80
      - 6006:6006
    command: >
      sh -c "yarn install &&
              if [ \"$$DOCKER_NODE_ENV\" = 'dev' ]; then
              yarn docker;
              else
              yarn build && npx serve -s dist -l 80
              fi"
